spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stock_prices?currentSchema=stock_prices
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
